# Generated by Django 4.2.2 on 2023-06-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=50)),
                ('description_site', models.CharField(max_length=1000, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('video_site', models.CharField(max_length=2000, null=True)),
                ('historique_site', models.CharField(max_length=2000, null=True)),
                ('atouts_site', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=50)),
                ('description_site', models.CharField(max_length=1000, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('video_stade', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=50)),
                ('description_ville', models.CharField(max_length=1000, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('video_ville', models.CharField(max_length=1000, null=True)),
                ('historique_ville', models.CharField(max_length=2000, null=True)),
                ('atouts_ville', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VillePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ville')),
            ],
        ),
        migrations.CreateModel(
            name='StadePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
                ('stade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stade')),
            ],
        ),
        migrations.AddField(
            model_name='stade',
            name='ville',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ville'),
        ),
        migrations.CreateModel(
            name='SiteTouristiquePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
                ('site_touristique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sitetouristique')),
            ],
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ville'),
        ),
    ]
